DOCS-10985-dw-multipart-sample-kt
mulesoft/docs-dataweave pull request #77
Opened 2021-10-28 17:52 UTC by kevintroller

Added iterate multipart example

2021-11-02 17:24 UTC, leansh requested changes

2021-11-02 17:24 UTC, leansh commented on modules/ROOT/pages/dataweave-formats-multipart.adoc
> +-34b21-'
```suggestion
--34b21--'
```

2021-11-02 17:24 UTC, leansh commented on modules/ROOT/pages/dataweave-formats-multipart.adoc
> +{{{}}
```suggestion
{
```

2021-11-02 18:01 UTC, leansh approved these changes

2021-11-02 18:11 UTC, dukesphere reviewed
suggestion

2021-11-02 18:11 UTC, dukesphere commented on modules/ROOT/pages/dataweave-formats-multipart.adoc
> +This example shows how DataWeave iterates through through all the parts of the payload and process the message individually.
```suggestion
This example shows how DataWeave iterates through all the parts of the payload and processes the each part individually.
```

2021-11-02 18:11 UTC, dukesphere commented on modules/ROOT/pages/dataweave-formats-multipart.adoc
> +This example shows how DataWeave iterates through through all the parts of the payload and process the message individually.
"and processes the message individually" is unclear. I assume it means "each part of the message"? I'm not sure but that's what I suggested above.

2021-11-03 13:49 UTC, dukesphere approved these changes

2021-11-04 15:06 UTC, merged