DOCS-12368-dw-object-sample-kt
mulesoft/docs-dataweave pull request #90
Opened 2021-12-13 20:57 UTC by kevintroller

Adding new DW example

2021-12-16 13:12 UTC, svacas requested changes

2021-12-16 13:12 UTC, svacas commented on modules/ROOT/pages/_partials/cookbook-dw/map-an-object-ex02/transform.dwl
> +valueSet(payload groupBy ((item, index) -> (item.FirstName ++ item.LastName ++ item.Age)) mapObject ((value, key, index) -> (index): {
`valueSet` is deprecated since 2.3, use `valuesOf` instead

2021-12-28 16:38 UTC, TomoDC commented on modules/ROOT/pages/_partials/cookbook-dw/map-an-object-ex02/transform.dwl
> +%dw 2.0
Maybe formatting the script:

```
%dw 2.0
output application/csv
---
valuesOf(
    payload 
        groupBy ((item, index) -> (
            item.FirstName ++ item.LastName ++ item.Age)) 
        mapObject ((value, key, index) -> 
            (index): {
                "Sr.No.": value."Sr.No." joinBy ":", 
                "FirstName": value.FirstName[0],
                "LastName": value.LastName[0],
                "Age": value.Age[0],
                "Team Name": value."Team Name" joinBy ":", 
                "Role": value.Role joinBy ":"
            })
)
```

2021-12-28 16:38 UTC, TomoDC commented on modules/ROOT/pages/dataweave-cookbook-map-an-object.adoc
> +This example uses the `mapObject` function to iterate through the elements in a table. If two rows have the same values in the `FirstName`, `LastName` or `Age` columns, the DataWeave script transform
```suggestion
This example uses the `mapObject` function to iterate through the keys and values of the object that results from using `groupBy` on the payload. If some objects of the input payload have the same values in the `FirstName`, `LastName` and `Age` keys, the DataWeave script transforms those objects into a single row in a CSV file. The remaining values in the `Team Name` and `Role` keys for those objects are concatenated with `:` in the single CSV row.
```
Transform from json objects to the CSV file

2021-12-28 16:38 UTC, TomoDC commented on modules/ROOT/pages/dataweave-cookbook-map-an-object.adoc
> +The following DataWeave examples use the `mapObject` function to iterate through the keys and values in each of the objects of the arrays.
```suggestion
The following DataWeave examples use the `mapObject` function to iterate through the keys and values of objects.
```
It does not iterate over arrays. The array are transformed by other functions to an object and the mapObject iterate through that object.

2021-12-28 16:38 UTC, TomoDC commented on modules/ROOT/pages/dataweave-cookbook-map-an-object.adoc
> +The DataWeave scripts merges the repeated values of columns `FirstName`, `LastName` or `Age` of rows `Sr.No. 2` and `Sr.No. 3`, and also rows `Sr.No. 5` and `Sr.No. 6`. These values are separated wit
```suggestion
The DataWeave script merges the repeated values of keys `FirstName`, `LastName` and `Age` of the objects with key-value `Sr.No. 2` and `Sr.No. 3`, and also `Sr.No. 5` and `Sr.No. 6`. These values are separated with `,` in the single CSV row. The values of the `Team Name` and `Role` for those objects are concatenated with `:` in the single CSV row.
```
From JSON objects to CSV rows.

2021-12-28 20:08 UTC, svacas requested changes

2021-12-28 20:08 UTC, svacas commented on modules/ROOT/pages/dataweave-cookbook-map-an-object.adoc
> +include::partial$cookbook-dw/map-an-object-ex02/out.json[]
change the file extension from `out.json` to `out.csv`

2021-12-28 22:35 UTC, luanamulesoft commented on modules/ROOT/pages/dataweave-cookbook-map-an-object.adoc
> +In the previous input example, `Sr.No. 2` and `Sr.No. 3`, and also `Sr.No. 5` and `Sr.No. 6` are exactly the same person because they have same first name, last name and age. However, `Sr.No. 4` is d
Suggestion: "In the previous input example, the object pair `Sr.No. 2` and `Sr.No. 3`, as well as the object pair `Sr.No. 5` and `Sr.No. 6`, refer to the same person, as they have the same first name, last name, and age. However, `Sr.No. 4` refers to a different person, as it has the same first and last name but a different age.

2021-12-28 22:39 UTC, luanamulesoft commented on modules/ROOT/pages/dataweave-cookbook-map-an-object.adoc
> +The DataWeave script merges the repeated values of keys `FirstName`, `LastName` and `Age` of the objects with key-value `Sr.No. 2` and `Sr.No. 3`, and also `Sr.No. 5` and `Sr.No. 6`. These values are
Suggestion: The DataWeave script merges the repeated values of `FirstName`, `LastName` and `Age` of the objects with key-value `Sr.No. 2` and `Sr.No. 3`, as well as `Sr.No. 5` and `Sr.No. 6`. These values are separated with `,` in the single CSV row. The values of `Team Name` and `Role` for those objects are concatenated with `:` in the single CSV row.

2021-12-28 22:40 UTC, luanamulesoft submitted a review, later dismissed

2021-12-29 14:54 UTC, luanamulesoft approved these changes

2021-12-29 16:31 UTC, svacas approved these changes

2022-02-15 18:43 UTC, kevintroller commented
Closing as creating new PR (verified commits) https://github.com/mulesoft/docs-dataweave/pull/109

2022-02-15 18:43 UTC, closed without merging